### ISSUE TITLE
Support for just enough items.

### ISSUE THREAD

**Issue by adex345** [CodeOfArdonia/TinkersConstruct-Fabric#1]
### Minecraft Version

1.20.1

### Fabric Version

0.16.9

### Fabric API Version

0.92.2

### Supporoform Version

3.6.5.1

### Describe your issue

Just enough items doesn't launch when this mod is on. Hephaestus is working normally.

### Other mods

just enough items

### Tried reproducing with just Tinkers?

Yes

### Performance Enchancers

Sodium

### Searched for known issues?

Checked pinned issues, Searched open issues, Searched closed issues

**Comment by IAFEnvoy** [comment]
No plan for support JEI, use Hephaestus instead
